import re

ECO_OPENING_NAMES = {
    "A00": "Uncommon Opening",
    "A01": "Nimzowitsch-Larsen Attack",
    "A02": "Bird's Opening",
    "A03": "Bird's Opening",
    "A04": "Reti Opening",
    "A05": "Reti Opening",
    "A06": "Reti Opening",
    "A07": "King's Indian Attack",
    "A08": "King's Indian Attack",
    "A09": "Reti Opening",
    "A10": "English Opening",
    "A13": "English Opening",
    "A15": "English Opening",
    "A16": "English Opening",
    "A17": "English Opening",
    "A20": "English Opening",
    "A21": "English Opening",
    "A22": "English Opening",
    "A25": "English Opening",
    "A27": "English Opening",
    "A28": "English Opening",
    "A29": "English Opening",
    "A30": "English Opening",
    "A34": "English Opening",
    "A35": "English Opening",
    "A36": "English Opening",
    "A40": "Queen's Pawn",
    "A41": "Queen's Pawn",
    "A42": "Modern Defense",
    "A43": "Old Benoni",
    "A45": "Indian Game",
    "A46": "Indian Game",
    "A47": "Queen's Indian",
    "A48": "King's Indian / East Indian",
    "A49": "King's Indian / East Indian",
    "A50": "Indian Game",
    "A51": "Budapest Gambit",
    "A52": "Budapest Gambit",
    "A53": "Old Indian",
    "A54": "Old Indian",
    "A55": "Old Indian",
    "A56": "Benoni Defense",
    "A57": "Benko Gambit",
    "A58": "Benko Gambit",
    "A59": "Benko Gambit",
    "A60": "Benoni Defense",
    "A65": "Benoni Defense",
    "A70": "Benoni Defense",
    "A80": "Dutch Defense",
    "A84": "Dutch Defense",
    "A85": "Dutch Defense",
    "A86": "Dutch Defense",
    "A87": "Dutch Defense",
    "A90": "Dutch Defense",
    "A96": "Dutch Defense",
    "B00": "King's Pawn Opening",
    "B01": "Scandinavian Defense",
    "B02": "Alekhine's Defense",
    "B03": "Alekhine's Defense",
    "B04": "Alekhine's Defense",
    "B05": "Alekhine's Defense",
    "B06": "Modern Defense",
    "B07": "Pirc Defense",
    "B08": "Pirc Defense",
    "B09": "Pirc Defense",
    "B10": "Caro-Kann Defense",
    "B11": "Caro-Kann Defense",
    "B12": "Caro-Kann Defense",
    "B13": "Caro-Kann Defense",
    "B14": "Caro-Kann Defense",
    "B15": "Caro-Kann Defense",
    "B16": "Caro-Kann Defense",
    "B17": "Caro-Kann Defense",
    "B18": "Caro-Kann Defense",
    "B19": "Caro-Kann Defense",
    "B20": "Sicilian Defense",
    "B21": "Sicilian Defense",
    "B22": "Sicilian Defense (Alapin)",
    "B23": "Sicilian Defense",
    "B24": "Sicilian Defense",
    "B25": "Sicilian Defense",
    "B26": "Sicilian Defense",
    "B27": "Sicilian Defense",
    "B28": "Sicilian Defense",
    "B29": "Sicilian Defense",
    "B30": "Sicilian Defense",
    "B31": "Sicilian Defense",
    "B32": "Sicilian Defense",
    "B33": "Sicilian Defense",
    "B34": "Sicilian Defense",
    "B35": "Sicilian Defense",
    "B36": "Sicilian Defense",
    "B37": "Sicilian Defense",
    "B38": "Sicilian Defense",
    "B39": "Sicilian Defense",
    "B40": "Sicilian Defense",
    "B41": "Sicilian Defense",
    "B42": "Sicilian Defense",
    "B43": "Sicilian Defense",
    "B44": "Sicilian Defense",
    "B45": "Sicilian Defense",
    "B46": "Sicilian Defense",
    "B47": "Sicilian Defense",
    "B48": "Sicilian Defense",
    "B49": "Sicilian Defense",
    "B50": "Sicilian Defense",
    "B51": "Sicilian Defense",
    "B52": "Sicilian Defense",
    "B53": "Sicilian Defense",
    "B54": "Sicilian Defense",
    "B55": "Sicilian Defense",
    "B56": "Sicilian Defense",
    "B57": "Sicilian Defense",
    "B58": "Sicilian Defense",
    "B59": "Sicilian Defense",
    "B60": "Sicilian Defense",
    "B70": "Sicilian Defense",
    "B80": "Sicilian Defense",
    "B86": "Sicilian Defense",
    "B88": "Sicilian Defense",
    "B89": "Sicilian Defense",
    "B90": "Sicilian Defense (Najdorf)",
    "B92": "Sicilian Defense (Najdorf)",
    "B94": "Sicilian Defense (Najdorf)",
    "B96": "Sicilian Defense (Najdorf)",
    "B97": "Sicilian Defense (Najdorf)",
    "B99": "Sicilian Defense (Najdorf)",
    "C00": "French Defense",
    "C01": "French Defense",
    "C02": "French Defense",
    "C03": "French Defense",
    "C05": "French Defense",
    "C06": "French Defense",
    "C10": "French Defense",
    "C11": "French Defense",
    "C12": "French Defense",
    "C15": "French Defense",
    "C18": "French Defense",
    "C20": "King's Pawn Game",
    "C21": "Center Game",
    "C22": "Center Game",
    "C23": "Bishop's Opening",
    "C24": "Bishop's Opening",
    "C25": "Vienna Game",
    "C26": "Vienna Game",
    "C27": "Vienna Game",
    "C28": "Vienna Game",
    "C29": "Vienna Game",
    "C30": "King's Gambit",
    "C31": "King's Gambit",
    "C32": "King's Gambit",
    "C33": "King's Gambit",
    "C34": "King's Gambit",
    "C35": "King's Gambit",
    "C36": "King's Gambit",
    "C37": "King's Gambit",
    "C38": "King's Gambit",
    "C39": "King's Gambit",
    "C40": "King's Knight Opening",
    "C41": "Philidor Defense",
    "C42": "Petrov's Defense",
    "C43": "Petrov's Defense",
    "C44": "King's Pawn Game",
    "C45": "Scotch Game",
    "C46": "Three Knights Opening",
    "C47": "Four Knights Game",
    "C48": "Four Knights Game",
    "C49": "Four Knights Game",
    "C50": "Italian Game",
    "C51": "Italian Game (Evans Gambit)",
    "C52": "Italian Game (Evans Gambit)",
    "C53": "Italian Game",
    "C54": "Italian Game",
    "C55": "Italian Game",
    "C56": "Italian Game",
    "C57": "Italian Game (Two Knights)",
    "C58": "Italian Game (Two Knights)",
    "C59": "Italian Game (Two Knights)",
    "C60": "Ruy Lopez",
    "C65": "Ruy Lopez",
    "C68": "Ruy Lopez",
    "C70": "Ruy Lopez",
    "C77": "Ruy Lopez",
    "C78": "Ruy Lopez",
    "C84": "Ruy Lopez",
    "C88": "Ruy Lopez",
    "C89": "Ruy Lopez",
    "C90": "Ruy Lopez",
    "C92": "Ruy Lopez",
    "C95": "Ruy Lopez",
    "C96": "Ruy Lopez",
    "C97": "Ruy Lopez",
    "C98": "Ruy Lopez",
    "C99": "Ruy Lopez",
    "D00": "Queen's Pawn Opening",
    "D01": "Richter-Veresov Attack",
    "D02": "Queen's Pawn Opening",
    "D03": "Torre Attack",
    "D04": "Queen's Pawn Opening",
    "D05": "Colle System",
    "D06": "Queen's Gambit",
    "D07": "Queen's Gambit Declined",
    "D08": "Queen's Gambit Declined",
    "D10": "Slav Defense",
    "D11": "Slav Defense",
    "D12": "Slav Defense",
    "D15": "Slav Defense",
    "D17": "Slav Defense",
    "D20": "Queen's Gambit Accepted",
    "D21": "Queen's Gambit Accepted",
    "D25": "Queen's Gambit Accepted",
    "D26": "Queen's Gambit Accepted",
    "D30": "Queen's Gambit Declined",
    "D31": "Queen's Gambit Declined",
    "D35": "Queen's Gambit Declined",
    "D37": "Queen's Gambit Declined",
    "D38": "Queen's Gambit Declined",
    "D43": "Semi-Slav Defense",
    "D44": "Semi-Slav Defense",
    "D45": "Semi-Slav Defense",
    "D46": "Semi-Slav Defense",
    "D47": "Semi-Slav Defense",
    "D50": "Queen's Gambit Declined",
    "D52": "Queen's Gambit Declined",
    "D53": "Queen's Gambit Declined",
    "D55": "Queen's Gambit Declined",
    "D58": "Queen's Gambit Declined",
    "D60": "Queen's Gambit Declined",
    "D70": "Neo-Grunfeld Defense",
    "D80": "Grunfeld Defense",
    "D85": "Grunfeld Defense",
    "D90": "Grunfeld Defense",
    "D94": "Grunfeld Defense",
    "D96": "Grunfeld Defense",
    "E00": "Catalan / Indian",
    "E01": "Catalan Opening",
    "E04": "Catalan Opening",
    "E06": "Catalan Opening",
    "E10": "Indian Game",
    "E11": "Bogo-Indian Defense",
    "E12": "Queen's Indian Defense",
    "E14": "Queen's Indian Defense",
    "E15": "Queen's Indian Defense",
    "E17": "Queen's Indian Defense",
    "E20": "Nimzo-Indian Defense",
    "E21": "Nimzo-Indian Defense",
    "E24": "Nimzo-Indian Defense",
    "E32": "Nimzo-Indian Defense",
    "E34": "Nimzo-Indian Defense",
    "E38": "Nimzo-Indian Defense",
    "E41": "Nimzo-Indian Defense",
    "E46": "Nimzo-Indian Defense",
    "E48": "Nimzo-Indian Defense",
    "E54": "Nimzo-Indian Defense",
    "E56": "Nimzo-Indian Defense",
    "E60": "King's Indian Defense",
    "E61": "King's Indian Defense",
    "E62": "King's Indian Defense",
    "E63": "King's Indian Defense",
    "E64": "King's Indian Defense",
    "E66": "King's Indian Defense",
    "E67": "King's Indian Defense",
    "E68": "King's Indian Defense",
    "E69": "King's Indian Defense",
    "E70": "King's Indian Defense",
    "E71": "King's Indian Defense",
    "E72": "King's Indian Defense",
    "E73": "King's Indian Defense",
    "E76": "King's Indian Defense",
    "E80": "King's Indian Defense",
    "E81": "King's Indian Defense",
    "E87": "King's Indian Defense",
    "E90": "King's Indian Defense",
    "E91": "King's Indian Defense",
    "E92": "King's Indian Defense",
    "E94": "King's Indian Defense",
    "E95": "King's Indian Defense",
    "E97": "King's Indian Defense",
    "E99": "King's Indian Defense",
}


def eco_base_opening_name(opening_name: str) -> str:
    name = str(opening_name or "").strip()
    if not name or name == "Unknown":
        return "Unknown"
    name = re.split(r"\s+\d+\.(?:\.\.)?", name, maxsplit=1)[0].strip()
    return name or "Unknown"


def build_eco_name_map(df) -> dict:
    eco_map = dict(ECO_OPENING_NAMES)
    if df is None or getattr(df, "empty", True):
        return eco_map
    if "opening_eco" not in df.columns or "opening_name" not in df.columns:
        return eco_map

    for eco, group in df.groupby("opening_eco"):
        eco_key = str(eco).strip().upper()
        if not eco_key or eco_key == "UNK" or eco_key in ECO_OPENING_NAMES:
            continue
        names = (
            group["opening_name"]
            .dropna()
            .map(eco_base_opening_name)
            .loc[lambda s: s != "Unknown"]
        )
        if names.empty:
            continue
        eco_map[eco_key] = names.mode().iloc[0]
    return eco_map


def format_eco_label(eco: str, eco_map: dict | None = None) -> str:
    eco_key = str(eco or "").strip().upper()
    if not eco_key or eco_key in {"UNK", "N/A"}:
        return eco_key or "UNK"
    lookup = eco_map if eco_map is not None else ECO_OPENING_NAMES
    name = lookup.get(eco_key) or ECO_OPENING_NAMES.get(eco_key)
    if not name:
        return eco_key
    return f"{eco_key} · {name}"
