/**
 * Book/ontology archive — ported from chess-coach pattern YAMLs
 * (Silman imbalances, Chess Structures, opening repertoires, Dvoretsky endgames).
 */

import type { KnowledgeCard } from "./knowledgePack";

export const BOOK_ARCHIVE: KnowledgeCard[] = [
  {
    id: "endgame_lucena",
    label: "Lucena Position",
    requireThemes: ["endgame_technique"],
    weight: 2,
    rules: [
      "Winning R+P vs R method: king in front of pawn on 7th, bridge with rook.",
      "Cut off enemy king; check to force space for the bridge.",
      "Reach Lucena structure; avoid Philidor drawing setups for the defender.",
    ],
    phases: ["endgame", "any"],
  },
  {
    id: "endgame_opposite_bishops",
    label: "Opposite-Bishop Ending",
    requireThemes: ["bishop_pair", "endgame_technique"],
    weight: 2,
    rules: [
      "Same-colored pawn majorities matter less; blockading on the right color is key.",
      "Extra pawns often insufficient if all on one wing and blockaded.",
      "Stronger side \u2014 create two widely separated passed pawns.",
      "Weaker side \u2014 blockade on the bishop's color, keep king active.",
    ],
    phases: ["endgame", "any"],
  },
  {
    id: "endgame_philidor",
    label: "Philidor Defence (Rook Ending)",
    requireThemes: ["endgame_technique"],
    weight: 2,
    rules: [
      "Defender keeps rook on 3rd rank until pawn reaches 6th, then checks from behind.",
      "Classic drawing technique vs R+P when king is cut off.",
      "Hold the 3rd-rank barrier; switch to rear checks at the right moment.",
    ],
    phases: ["endgame", "any"],
  },
  {
    id: "imbalance_bishop_pair",
    label: "Bishop Pair",
    requireThemes: ["bishop_pair"],
    weight: 2,
    rules: [
      "Bishop pair thrives in open positions; avoid locking the centre.",
      "Side without the pair seeks closed structures or knight outposts.",
      "Open lines, trade into endgames where bishops rake both wings.",
    ],
    phases: ["any"],
  },
  {
    id: "imbalance_king_safety",
    label: "King Safety / Attack",
    requireThemes: ["king_safety"],
    weight: 2,
    rules: [
      "When kings face opposite wings, pawn storms beat slow manoeuvres.",
      "Extra attackers near the king outweigh small material if files open.",
      "Open lines toward their king; don't trade attacking pieces lightly.",
    ],
    phases: ["middlegame", "any"],
  },
  {
    id: "imbalance_material",
    label: "Material Imbalance",
    requireThemes: ["exchanges"],
    weight: 2,
    rules: [
      "Convert material by simplifying into a clear endgame unless the attack is stronger.",
      "Down material: keep pieces, seek complications or perpetual ideas.",
      "Ahead — trade pieces not pawns; behind — keep tension.",
    ],
    phases: ["any"],
  },
  {
    id: "imbalance_opposite_bishops",
    label: "Opposite-Colored Bishops",
    requireThemes: ["bishop_pair", "endgame_technique"],
    weight: 2,
    rules: [
      "Middlegame \u2014 attack is stronger; defender struggles to cover the weak color complex.",
      "Pure opposite-bishop endgames are often drawish even a pawn down.",
      "Attacker \u2014 pile on the color the enemy bishop cannot defend.",
      "Defender \u2014 trade into a pure opposite-bishop ending if down material.",
    ],
    phases: ["any"],
  },
  {
    id: "imbalance_space",
    label: "Space Advantage",
    requireThemes: ["space"],
    weight: 2,
    rules: [
      "Side with more space manoeuvres behind the pawn wall; avoid premature trades of attacking pieces.",
      "Cramped side seeks pawn breaks and piece trades to free the position.",
      "Space side — improve pieces, restrain breaks, prepare a wing attack.",
      "Cramped side — timely break (...c5/...e5/...f5) or simplify.",
    ],
    phases: ["middlegame", "any"],
  },
  {
    id: "opening_caro_kann",
    label: "Caro-Kann Defence",
    requireThemes: ["named_opening", "development", "centre", "opening_plan", "opening_caro_kann"],
    weight: 3,
    rules: [
      "Solid ...c6/...d5 structure; Black often develops the light-squared bishop outside the chain.",
      "Endgames can favour Black's structure if White overpresses.",
      "Black \u2014 solid development, timely ...c5, good bishop.",
      "White \u2014 space, piece activity, attack before the position simplifies.",
    ],
    phases: ["opening", "any"],
  },
  {
    id: "opening_french",
    label: "French Defence",
    requireThemes: ["named_opening", "development", "centre", "opening_plan", "opening_french", "opening_french_defence", "opening_french_defense"],
    weight: 3,
    rules: [
      "Black challenges e4 with ...d5; the light-squared bishop is the problem child.",
      "Plans revolve around ...c5 breaks and play against a fixed e5 pawn in the Advance.",
      "Black \u2014 ...c5, pressure d4, free the c8 bishop later.",
      "White \u2014 space on kingside or central bind; meet ...c5 carefully.",
    ],
    phases: ["opening", "any"],
  },
  {
    id: "opening_kings_indian",
    label: "King's Indian Defence",
    requireThemes: ["named_opening", "development", "centre", "opening_plan", "opening_indian", "opening_king_s_indian", "opening_kings_indian"],
    weight: 3,
    rules: [
      "Black fianchetto and often strikes with ...e5 or ...c5; kingside attacks are thematic after a closed centre.",
      "White chooses Classical, S\u00e4misch, or Fianchetto setups \u2014 space vs Black's dynamic breaks.",
      "Black \u2014 ...f5 attack or queenside counterplay depending on the line.",
      "White \u2014 central bind, queenside expansion, meet ...f5 with piece play.",
    ],
    phases: ["opening", "any"],
  },
  {
    id: "opening_queens_gambit",
    label: "Queen's Gambit / QGD",
    requireThemes: ["named_opening", "development", "centre", "opening_plan", "opening_queens_gambit", "opening_queen_s_gambit", "opening_qgd"],
    weight: 3,
    rules: [
      "Fight for d5/c4; Exchange/Carlsbad often leads to minority-attack structures.",
      "Black chooses solid (...e6) or more active systems (Tarrasch, Semi-Slav ideas).",
      "White \u2014 pressure d5, minority attack, or central break e4.",
      "Black \u2014 ...c5/...e5 freeing breaks, piece activity.",
    ],
    phases: ["opening", "any"],
  },
  {
    id: "opening_sicilian_dragon",
    label: "Sicilian Dragon",
    requireThemes: ["named_opening", "development", "centre", "opening_plan", "opening_sicilian", "opening_dragon"],
    weight: 3,
    rules: [
      "Fianchetto bishop on g7 is Black's soul; exchange on g7 is often decisive.",
      "Yugoslav Attack: opposite-side castling race \u2014 White h-pawn, Black c-file.",
      "Exchange sac on c3 is a thematic Dragon resource.",
      "Black: ...Rc8, ...Nc4, queenside attack.",
      "White: Bh6, h4\u2013h5, open h-file.",
    ],
    phases: ["opening", "any"],
  },
  {
    id: "opening_sicilian_najdorf",
    label: "Sicilian Najdorf",
    requireThemes: ["named_opening", "development", "centre", "opening_plan", "opening_sicilian", "opening_najdorf"],
    weight: 3,
    rules: [
      "...a6 restrains Nb5 and prepares ...b5 queenside expansion.",
      "English Attack (Be3, f3, Qd2, g4) is the main theoretical battleground.",
      "Central breaks ...d5 / ...e5 define the middlegame character.",
      "Black: ...b5, ...Bb7, timely central break.",
      "White: kingside pawn storm or classical pressure on d6.",
    ],
    phases: ["opening", "any"],
  },
  {
    id: "opening_sicilian_scheveningen",
    label: "Sicilian Scheveningen",
    requireThemes: ["named_opening", "development", "centre", "opening_plan", "opening_sicilian", "opening_scheveningen"],
    weight: 3,
    rules: [
      "Black keeps flexible d6\u2013e6 centre; waits for White's commitment.",
      "Classic breaks: ...d5 and sometimes ...e5; watch d5 hole if e5 is played early.",
      "White chooses English Attack, Keres Attack, or classical piece play.",
      "Black: develop, castle, time ...d5; use c-file.",
      "White: space on kingside or central bind with f4/e5 ideas.",
    ],
    phases: ["opening", "any"],
  },
  {
    id: "structure_doubled_pawns",
    label: "Doubled Pawns",
    requireThemes: ["pawn_breaks"],
    weight: 3,
    rules: [
      "Doubled pawns are often static weaknesses but can open files for rooks.",
      "Trade into endgames only if the doubled complex is not easily targeted.",
      "Sometimes accepted voluntarily for bishop pair or open lines.",
      "Owner: use the open file, undouble if clean chance appears.",
      "Opponent: fix and pressure the front pawn of the double.",
    ],
    phases: ["any"],
  },
  {
    id: "structure_hanging_pawns",
    label: "Hanging Pawns",
    requireThemes: ["hanging_pawns"],
    weight: 3,
    rules: [
      "Hanging pawns control space and open lines but can become fixed targets.",
      "Owner wants dynamic breaks (c5/d5 or c4/d4) and piece activity.",
      "Opponent restrains the duo, induces an advance, then attacks the resulting weaknesses.",
      "Owner: prepare the break, keep pieces behind the pawns, avoid a premature push.",
      "Opponent: blockade, pressure with major pieces on half-open files.",
    ],
    phases: ["middlegame", "any"],
  },
  {
    id: "structure_hedgehog",
    label: "Hedgehog",
    requireThemes: ["space", "pawn_breaks", "prophylaxis"],
    weight: 3,
    rules: [
      "Black sits behind the 6th-rank pawns and waits for ...b5/...d5 breaks.",
      "White must not overextend; watch tactical shots on the long diagonals.",
      "Black \u2014 patience, then explosive ...b5 or ...d5.",
      "White \u2014 restrain breaks, probe weaknesses, avoid loose pieces.",
    ],
    phases: ["middlegame", "any"],
  },
  {
    id: "structure_iqp",
    label: "Isolated Queen Pawn",
    requireThemes: ["iqp"],
    weight: 3,
    rules: [
      "Side with IQP seeks activity, kingside attack, and piece play before the endgame.",
      "Opponent blockades the pawn (often on d5/d4), trades pieces, aims for a favorable endgame.",
      "Outposts on c5/e5 (or c4/e4) are classic for the IQP side's knights.",
      "IQP side: lift a rook, use open c/e files, avoid wholesale exchanges.",
      "Defender: sit on the blockade square, trade queens, pressure the isolani.",
    ],
    phases: ["middlegame", "any"],
  },
  {
    id: "structure_maroczy_bind",
    label: "Mar\u00f3czy Bind",
    requireThemes: ["space", "pawn_breaks"],
    weight: 3,
    rules: [
      "White pawns on c4+e4 clamp ...d5; Black plays for ...b5/...f5 or a delayed ...d5.",
      "White avoids careless piece trades that release the bind without compensation.",
      "White \u2014 squeeze, knight to d5/c4, queenside space.",
      "Black \u2014 ...a6/...b5, piece pressure on c4, or ...f5 breaks.",
    ],
    phases: ["middlegame", "any"],
  },
  {
    id: "structure_minority_attack",
    label: "Minority Attack (Carlsbad)",
    requireThemes: ["minority_attack"],
    weight: 3,
    rules: [
      "Side with fewer queenside pawns advances b-pawn to create a backward c-pawn or open file.",
      "Classic in QGD Exchange / Carlsbad: White plays b4\u2013b5 vs Black's c6\u2013d5.",
      "Defender meets b5 carefully; piece play on kingside is the usual counter.",
      "Attacker: b4, a3, Rb1, b5, fix or open the c-file.",
      "Defender: ...b5 clamp, or kingside counterplay before the structure cracks.",
    ],
    phases: ["middlegame", "any"],
  },
  {
    id: "structure_open_c_file",
    label: "Open / Half-Open c-file",
    requireThemes: ["open_c_file", "open_file"],
    weight: 3,
    rules: [
      "Rooks belong on open files; the seventh rank and entry squares matter.",
      "In IQP/hanging positions the c-file is often the highway for pressure.",
      "Double rooks on c, look for entry on c7/c2 or trade into favorable ending.",
    ],
    phases: ["middlegame", "any"],
  },
  {
    id: "structure_open_e_file",
    label: "Open / Half-Open e-file",
    requireThemes: ["open_file"],
    weight: 3,
    rules: [
      "Central files host rooks after exchanges on e4/e5; entry on e7/e2 is thematic.",
      "Often paired with IQP or open games after ...exd4 / dxe5.",
      "Occupy e-file, invade the 7th, support central outposts.",
    ],
    phases: ["middlegame", "any"],
  },
  {
    id: "structure_passed_pawn",
    label: "Passed Pawn",
    requireThemes: ["passed_pawn"],
    weight: 3,
    rules: [
      "Passed pawns must be pushed; blockade them with a piece when defending.",
      "Outside passers distract the enemy king in endgames.",
      "Owner \u2014 escort with king/rook; create a second weakness.",
      "Defender \u2014 blockade, trade the passer, or create counterplay elsewhere.",
    ],
    phases: ["any"],
  },
  {
    id: "structure_pawn_chain",
    label: "Pawn Chain / Locked Centre",
    requireThemes: ["pawn_chain"],
    weight: 3,
    rules: [
      "Attack the base of the chain; play on the side where your chain points.",
      "Breaks (...c5/...f6 or c4/f4) define the plans.",
      "Chain owner \u2014 space and wing attack in the chain direction.",
      "Opponent \u2014 undermine the base and open a file.",
    ],
    phases: ["middlegame", "any"],
  },
  {
    id: "opening_london",
    label: "London System",
    requireThemes: [
      "named_opening",
      "development",
      "centre",
      "opening_plan",
      "opening_london",
    ],
    weight: 3,
    rules: [
      "Solid Bf4/Bd3 setup with e3–c3; White aims for controlled breaks (e4/c4), not random pawn storms.",
      "Knights often head for e5 and d2–f3; the b1–h7 battery is a recurring attacking idea.",
      "Black tests the bishop with ...c5/...Qb6; White must decide whether to retreat, sac, or reinforce.",
      "White — harmony first, then a clear break; Black — challenge d4 and free the c8 bishop.",
    ],
    phases: ["opening", "any"],
  },
  {
    id: "opening_ruy_lopez",
    label: "Ruy Lopez",
    requireThemes: [
      "named_opening",
      "development",
      "centre",
      "opening_plan",
      "opening_ruy_lopez",
    ],
    weight: 3,
    rules: [
      "White pressures e5 and prepares c3–d4; Black chooses Marshall, Berlin, or Closed plans.",
      "Closed Ruy: Re1, Nbd2–f1–g3 manoeuvres before forcing the centre open.",
      "When the centre opens, piece activity and the bishop pair often outweigh a pawn.",
      "White — squeeze e5, expand queenside or break with d4; Black — timely ...d5 or queenside counterplay.",
    ],
    phases: ["opening", "any"],
  },
  {
    id: "opening_italian",
    label: "Italian Game",
    requireThemes: [
      "named_opening",
      "development",
      "centre",
      "opening_plan",
      "opening_italian",
    ],
    weight: 3,
    rules: [
      "Fight for d4/d5 and the long diagonals; Bc4 and ...Bc5 set the early tension.",
      "Choose c3–d4 races or quiet Pianissimo (d3) consciously — they are different middlegames.",
      "Knights on e5/e4 are thematic; challenge them or accept a lasting bind.",
      "Both sides: develop, castle, then strike the centre or the soft f2/f7 points.",
    ],
    phases: ["opening", "any"],
  },
  {
    id: "opening_scandinavian",
    label: "Scandinavian Defence",
    requireThemes: [
      "named_opening",
      "development",
      "centre",
      "opening_plan",
      "opening_scandinavian",
    ],
    weight: 3,
    rules: [
      "...d5 forces early queen choices (...Qa5/...Qd6/...Qd8) that reshape development.",
      "Black develops fast, castles, then meets White space with ...c6/...e6 or ...c5.",
      "Watch Nb5/Bd2 discoveries against an exposed queen.",
      "White — space and tempo on the queen; Black — solid structure and piece activity.",
    ],
    phases: ["opening", "any"],
  },
  {
    id: "opening_petroff",
    label: "Petroff Defence",
    requireThemes: [
      "named_opening",
      "development",
      "centre",
      "opening_plan",
      "opening_petroff",
    ],
    weight: 3,
    rules: [
      "Symmetrical e4–e5 fight — equality from accurate trades and timely ...d5/...c5.",
      "Avoid drifting; improve the worst piece and meet kingside space with central counters.",
      "When files open, the first side to mobilize rooks often seizes the initiative.",
      "White — try for a lasting bind; Black — neutralize and trade into a healthy ending.",
    ],
    phases: ["opening", "any"],
  },
  {
    id: "opening_english",
    label: "English Opening",
    requireThemes: [
      "named_opening",
      "development",
      "centre",
      "opening_plan",
      "opening_english",
    ],
    weight: 3,
    rules: [
      "c4 fights for d5 without early e-pawn commitment — Botvinnik, Symmetrical, or reversed Sicilian.",
      "Clamp ...d5, expand with b4 or e3–d4, use the fianchetto long diagonal.",
      "If Black breaks (...d5/...b5), activity on open files beats clinging to a dead bind.",
      "White — squeeze and space; Black — timely central or queenside breaks.",
    ],
    phases: ["opening", "any"],
  },
  {
    id: "mg_imbalance_silman",
    label: "Silman Imbalances (Middlegame)",
    requireThemes: ["planning", "piece_activity", "initiative"],
    weight: 2,
    rules: [
      "List imbalances (king safety, material, structure, space, activity, development) and play toward your plusses.",
      "Improve the worst-placed piece that hits today's target before inventing a new plan.",
      "Two candidates: ask which plan each serves — drop the move that fights yesterday's position.",
    ],
    phases: ["middlegame", "any"],
  },
  {
    id: "mg_calculation",
    label: "Calculation Habits",
    requireThemes: ["forcing_moves", "tactics", "missed_opportunity"],
    weight: 2,
    rules: [
      "Checks, captures, and threats first — quiet improving moves wait until forcing lines are clear.",
      "Compare their best reply, not the reply you want; stop when the line no longer forces.",
      "If a tactic fails by one tempo, look for a preparatory move that wins that tempo.",
    ],
    phases: ["middlegame", "any"],
  },
  {
    id: "endgame_opposition",
    label: "Opposition & King Activity",
    requireThemes: ["endgame_technique"],
    weight: 2,
    rules: [
      "In pawn endings, opposition and key squares decide — the active king is a fighting piece.",
      "Do not rush pawn moves that gift the opponent opposition or create fixed targets.",
      "Create a passed pawn, then use the king to escort or to invade the opposite wing.",
    ],
    phases: ["endgame", "any"],
  },
  {
    id: "endgame_rook_activity",
    label: "Rook Activity",
    requireThemes: ["endgame_technique", "open_file", "passed_pawn"],
    weight: 2,
    rules: [
      "Active rook behind a passer (or cutting the enemy king) beats a passive defender on the back rank.",
      "Trade into Lucena shapes when winning; hold Philidor barriers when defending R+P.",
      "Give checks from a distance when the enemy king must shepherd a passer.",
    ],
    phases: ["endgame", "any"],
  },
];
