/* Auto-generated by chess-coach export-mobile-pack. Do not edit by hand. */
/* PDF ingest + masters DB stay offline in CLI; app loads this derived pack only. */

export type DerivedFrequentLine = {
  sanLine: string;
  count: number;
  eco: string;
};

export type DerivedCoachEntry = {
  id: string;
  text: string;
  book: string;
  chapter: string;
  themes: string[];
  motifs: string[];
  ecoHints: string[];
  frequentLines: DerivedFrequentLine[];
};

export type DerivedCoachPack = {
  version: number;
  generatedBy: string;
  entryCount: number;
  entries: DerivedCoachEntry[];
};

export const DERIVED_COACH_PACK: DerivedCoachPack = {
  "version": 1,
  "generatedBy": "chess-coach export-mobile-pack",
  "entryCount": 8,
  "entries": [
    {
      "id": "9bc2703a6265ac404dbebffe",
      "text": "Addressing these two difficulties is exactly the purpose of this book. Chess Structures -A Grandmaster Guide is an excellent selection of model games. By studying the 140 games and fragments in this book, the reader will learn many of the most important plans, patterns and ideas in chess. Themes: pawn structures, isolated queen pawn, carlsbad structure,…",
      "book": "Chess Structures: A Grandmaster Guide",
      "chapter": "body",
      "themes": [
        "pawn structures",
        "isolated queen pawn",
        "carlsbad structure",
        "king's indian structures",
        "strategic planning"
      ],
      "motifs": [
        "pawn structures",
        "isolated queen pawn",
        "carlsbad structure",
        "king's indian structures",
        "strategic planning"
      ],
      "ecoHints": [
        "E60",
        "E90",
        "D26"
      ],
      "frequentLines": [
        {
          "sanLine": "d4 Nf6 Nf3 g6 c4 Bg7 Nc3 O-O e4 d6",
          "count": 15,
          "eco": "E60"
        },
        {
          "sanLine": "d4 Nf6 Nf3 g6 c4 Bg7 g3 O-O Bg2 d6",
          "count": 6,
          "eco": "E60"
        },
        {
          "sanLine": "d4 Nf6 Nf3 g6 c4 Bg7 Nc3 O-O Bg5 h6",
          "count": 4,
          "eco": "E60"
        },
        {
          "sanLine": "d4 Nf6 Nf3 g6 c4 Bg7 Nc3 O-O Bg5 d6",
          "count": 3,
          "eco": "E60"
        }
      ]
    },
    {
      "id": "71e437c73a3227defd24bb83",
      "text": "io's detailed explanations allow the reader to identify the key elements in each example. Moreover, each game constitutes a building block toward the understanding of the structure as a whole. I am certain the readers of this book will find it both useful and entertaining. Themes: opening, pawn structures, isolated queen pawn, carlsbad structure.",
      "book": "Chess Structures: A Grandmaster Guide",
      "chapter": "body",
      "themes": [
        "opening",
        "pawn structures",
        "isolated queen pawn",
        "carlsbad structure",
        "king's indian structures",
        "strategic planning"
      ],
      "motifs": [
        "opening",
        "pawn structures",
        "isolated queen pawn",
        "carlsbad structure",
        "king's indian structures",
        "strategic planning"
      ],
      "ecoHints": [
        "E60",
        "E90",
        "D26"
      ],
      "frequentLines": [
        {
          "sanLine": "d4 Nf6 Nf3 g6 c4 Bg7 Nc3 O-O e4 d6",
          "count": 15,
          "eco": "E60"
        },
        {
          "sanLine": "d4 Nf6 Nf3 g6 c4 Bg7 g3 O-O Bg2 d6",
          "count": 6,
          "eco": "E60"
        },
        {
          "sanLine": "d4 Nf6 Nf3 g6 c4 Bg7 Nc3 O-O Bg5 h6",
          "count": 4,
          "eco": "E60"
        },
        {
          "sanLine": "d4 Nf6 Nf3 g6 c4 Bg7 Nc3 O-O Bg5 d6",
          "count": 3,
          "eco": "E60"
        }
      ]
    },
    {
      "id": "ab558cc630927093de10454e",
      "text": ", Quality Chess 20 10 De la Villa: Dismantling the Sicilian, New in Chess 20 10 Delchev & Semkov: 7he Safest Sicilian, Chess Stars 2006 Gligoric: King's Indian Defence: Mar de! Plata Variation, Batsford 2003 Grau: Tratado General De Ajedrez, Ediciones Colihue 19 98 Kasparov: 7he Test of Time, Pergamon 1986 Polugaevsky: 7he Sicilian Labyrinth: Volumes I &…",
      "book": "Chess Structures: A Grandmaster Guide",
      "chapter": "body",
      "themes": [
        "sicilian",
        "king's indian",
        "pawn structures",
        "isolated queen pawn",
        "carlsbad structure",
        "king's indian structures",
        "strategic planning"
      ],
      "motifs": [
        "opening.kings_indian",
        "sicilian",
        "king's indian",
        "pawn structures",
        "isolated queen pawn",
        "carlsbad structure",
        "king's indian structures",
        "strategic planning"
      ],
      "ecoHints": [
        "B90",
        "B70",
        "B80"
      ],
      "frequentLines": [
        {
          "sanLine": "e4 c5 Nf3 d6 d4 cxd4 Nxd4 Nf6 Nc3 a6",
          "count": 60,
          "eco": "B90"
        },
        {
          "sanLine": "e4 c5 Nf3 d6 d4 cxd4 Nxd4 Nf6 Nc3 g6",
          "count": 57,
          "eco": "B70"
        },
        {
          "sanLine": "e4 c5 Nf3 e6 d4 cxd4 Nxd4 Nf6 Nc3 d6",
          "count": 32,
          "eco": "B80"
        },
        {
          "sanLine": "e4 c5 Nf3 d6 d4 cxd4 Nxd4 Nf6 Nc3 e6",
          "count": 23,
          "eco": "B80"
        }
      ]
    },
    {
      "id": "cd3ef6a25dd884e01f6da95d",
      "text": "implicitly divided into five classes or families, each of which is more closely associated with one particular type of opening. Learning all structures within a family is very useful, as players must frequently decide between two options that yield different, yet related, structures. It is helpful to know which structure will prove more favourable. Themes:…",
      "book": "Chess Structures: A Grandmaster Guide",
      "chapter": "body",
      "themes": [
        "opening",
        "queen's gambit",
        "pawn structures",
        "isolated queen pawn",
        "carlsbad structure",
        "king's indian structures",
        "strategic planning"
      ],
      "motifs": [
        "opening.queens_gambit",
        "opening",
        "queen's gambit",
        "pawn structures",
        "isolated queen pawn",
        "carlsbad structure",
        "king's indian structures",
        "strategic planning"
      ],
      "ecoHints": [
        "E60",
        "E90",
        "D30"
      ],
      "frequentLines": [
        {
          "sanLine": "d4 Nf6 Nf3 g6 c4 Bg7 Nc3 O-O e4 d6",
          "count": 15,
          "eco": "E60"
        },
        {
          "sanLine": "d4 Nf6 Nf3 g6 c4 Bg7 g3 O-O Bg2 d6",
          "count": 6,
          "eco": "E60"
        },
        {
          "sanLine": "d4 Nf6 Nf3 g6 c4 Bg7 Nc3 O-O Bg5 h6",
          "count": 4,
          "eco": "E60"
        },
        {
          "sanLine": "d4 Nf6 Nf3 g6 c4 Bg7 Nc3 O-O Bg5 d6",
          "count": 3,
          "eco": "E60"
        }
      ]
    },
    {
      "id": "dbf2845f87438d80ce569499",
      "text": "Typical openings would be the Queen's Gambit Orthodox Defence, the Slav or the Queen's Indian Defence, but there are many others, such as the Scandinavian, the Caro-Kann or the Ala pin Variation against the Sicilian Defence. This family encompasses Chapters 1 through 7. In addition, I discuss the Panov structure in the Caro-Kann and the 3-3 vs. Themes:…",
      "book": "Chess Structures: A Grandmaster Guide",
      "chapter": "body",
      "themes": [
        "opening",
        "sicilian",
        "caro-kann",
        "queen's gambit",
        "pawn structures",
        "isolated queen pawn",
        "carlsbad structure",
        "king's indian structures",
        "strategic planning"
      ],
      "motifs": [
        "opening.queens_gambit",
        "structure.hedgehog",
        "opening.caro_kann",
        "opening",
        "sicilian",
        "caro-kann",
        "queen's gambit",
        "pawn structures",
        "isolated queen pawn",
        "carlsbad structure"
      ],
      "ecoHints": [
        "B90",
        "B70",
        "B80"
      ],
      "frequentLines": [
        {
          "sanLine": "e4 c5 Nf3 d6 d4 cxd4 Nxd4 Nf6 Nc3 a6",
          "count": 60,
          "eco": "B90"
        },
        {
          "sanLine": "e4 c5 Nf3 d6 d4 cxd4 Nxd4 Nf6 Nc3 g6",
          "count": 57,
          "eco": "B70"
        },
        {
          "sanLine": "e4 c5 Nf3 e6 d4 cxd4 Nxd4 Nf6 Nc3 d6",
          "count": 32,
          "eco": "B80"
        },
        {
          "sanLine": "e4 c5 Nf3 d6 d4 cxd4 Nxd4 Nf6 Nc3 e6",
          "count": 23,
          "eco": "B80"
        }
      ]
    },
    {
      "id": "f84090915c02be8487dfedc7",
      "text": "e7-e6; and then Hedgehog and Maroczy positions. This family spans Chapters 8 through 11. The Scheveningen and Dragon structures are discussed in Chapter 22 . Themes: opening, sicilian, pawn structures, isolated queen pawn.",
      "book": "Chess Structures: A Grandmaster Guide",
      "chapter": "body",
      "themes": [
        "opening",
        "sicilian",
        "pawn structures",
        "isolated queen pawn",
        "carlsbad structure",
        "king's indian structures",
        "strategic planning"
      ],
      "motifs": [
        "structure.hedgehog",
        "opening.sicilian_scheveningen",
        "opening.sicilian_dragon",
        "opening",
        "sicilian",
        "pawn structures",
        "isolated queen pawn",
        "carlsbad structure",
        "king's indian structures",
        "strategic planning"
      ],
      "ecoHints": [
        "B90",
        "B70",
        "B80"
      ],
      "frequentLines": [
        {
          "sanLine": "e4 c5 Nf3 d6 d4 cxd4 Nxd4 Nf6 Nc3 a6",
          "count": 60,
          "eco": "B90"
        },
        {
          "sanLine": "e4 c5 Nf3 d6 d4 cxd4 Nxd4 Nf6 Nc3 g6",
          "count": 57,
          "eco": "B70"
        },
        {
          "sanLine": "e4 c5 Nf3 e6 d4 cxd4 Nxd4 Nf6 Nc3 d6",
          "count": 32,
          "eco": "B80"
        },
        {
          "sanLine": "e4 c5 Nf3 d6 d4 cxd4 Nxd4 Nf6 Nc3 e6",
          "count": 23,
          "eco": "B80"
        }
      ]
    },
    {
      "id": "d99c6dcfa7afbaf2e32770b7",
      "text": "which is typically known as a Benoni-type position, while Chapter 13 studies the alternative exd5. The related Benko structure is discussed in Chapter 22. Family Four: King's Indian lbis family of five chapters is devoted to the multiple types of structure arising from the King's Indian Defence and its relatives. Themes: king's indian, ruy lopez, pawn…",
      "book": "Chess Structures: A Grandmaster Guide",
      "chapter": "body",
      "themes": [
        "king's indian",
        "ruy lopez",
        "pawn structures",
        "isolated queen pawn",
        "carlsbad structure",
        "king's indian structures",
        "strategic planning"
      ],
      "motifs": [
        "opening.kings_indian",
        "opening.french",
        "king's indian",
        "ruy lopez",
        "pawn structures",
        "isolated queen pawn",
        "carlsbad structure",
        "king's indian structures",
        "strategic planning"
      ],
      "ecoHints": [
        "E60",
        "E90",
        "C60"
      ],
      "frequentLines": [
        {
          "sanLine": "d4 Nf6 Nf3 g6 c4 Bg7 Nc3 O-O e4 d6",
          "count": 15,
          "eco": "E60"
        },
        {
          "sanLine": "d4 Nf6 Nf3 g6 c4 Bg7 g3 O-O Bg2 d6",
          "count": 6,
          "eco": "E60"
        },
        {
          "sanLine": "d4 Nf6 Nf3 g6 c4 Bg7 Nc3 O-O Bg5 h6",
          "count": 4,
          "eco": "E60"
        },
        {
          "sanLine": "d4 Nf6 Nf3 g6 c4 Bg7 Nc3 O-O Bg5 d6",
          "count": 3,
          "eco": "E60"
        }
      ]
    },
    {
      "id": "36d2fa7db7a75a3a14cf533f",
      "text": "10 Chess Structures - A Grandmaster Guide Family Five: French This family of three chapters studies the pawn chains that typically arise in the French Defence. It should be noted that such structures often occur in the Sicilian, the anti-Sicilian, the English Opening, the Catalan and many others. Miscellaneous Chapter As you may see from the list above,…",
      "book": "Chess Structures: A Grandmaster Guide",
      "chapter": "body",
      "themes": [
        "opening",
        "sicilian",
        "french",
        "english",
        "pawn structures",
        "isolated queen pawn",
        "carlsbad structure",
        "king's indian structures",
        "strategic planning"
      ],
      "motifs": [
        "opening.french",
        "structure.pawn_chain",
        "opening",
        "sicilian",
        "french",
        "english",
        "pawn structures",
        "isolated queen pawn",
        "carlsbad structure",
        "king's indian structures"
      ],
      "ecoHints": [
        "B90",
        "B70",
        "B80"
      ],
      "frequentLines": [
        {
          "sanLine": "e4 c5 Nf3 d6 d4 cxd4 Nxd4 Nf6 Nc3 a6",
          "count": 60,
          "eco": "B90"
        },
        {
          "sanLine": "e4 c5 Nf3 d6 d4 cxd4 Nxd4 Nf6 Nc3 g6",
          "count": 57,
          "eco": "B70"
        },
        {
          "sanLine": "e4 c5 Nf3 e6 d4 cxd4 Nxd4 Nf6 Nc3 d6",
          "count": 32,
          "eco": "B80"
        },
        {
          "sanLine": "e4 c5 Nf3 d6 d4 cxd4 Nxd4 Nf6 Nc3 e6",
          "count": 23,
          "eco": "B80"
        }
      ]
    }
  ]
} as const;
